Rename Void to Void_ since it is a reserved keyword in PHP7.1
Fixing the followint failure:

1) phpDocumentor\Reflection\TypeResolverTest::testResolvingKeywords with
data set #15 ('void', 'phpDocumentor\Reflection\Types\Void')
PHPUnit_Framework_Exception: Argument #1 (No Value) of
PHPUnit_Framework_Assert::assertInstanceOf() must be a class or
interface name